### ISSUE TITLE
Permission denied first launch

### ISSUE THREAD

**Issue by Antexa** [hardware/selfoss#3]
Hello, 

I ran into an issue when I try to run selfoss for the first time

Logs from docker logs -f selfoss : 

> user@ks:~$ sudo docker logs -f selfoss
> ls: /selfoss/data/*/: No such file or directory
> touch(): Unable to create file data/sqlite/selfoss.db because Permission denied
> The stream or file "/selfoss/data/logs/default.log" could not be opened: failed to open stream: Permission denied [/selfoss/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107]

> user@ks:/mnt/docker/selfoss$ ls -la
> total 32
> drwxr-xr-x 7  991  991 4096 Aug 28 11:14 .
> drwxr-xr-x 7 root root 4096 Aug 28 11:14 ..
> drwxr-xr-x 2 root root 4096 Aug 28 11:14 cache
> -rw-r--r-- 1 root root  760 Aug 28 11:14 config.ini
> drwxr-xr-x 2 root root 4096 Aug 28 11:14 favicons
> drwxr-xr-x 2 root root 4096 Aug 28 11:14 logs
> drwxr-xr-x 2 root root 4096 Aug 28 11:14 sqlite
> drwxr-xr-x 2 root root 4096 Aug 28 11:14 thumbnails

My docker-compose file does not specify a particular user.

**Comment by hardware** [comment]
I don't have this error on my end, even with the last update. Can you give me the result of `docker info` and your docker-compose file ?

**Comment by Antexa** [comment]
Docker info : 

> Containers: 7
>  Running: 6
>  Paused: 0
>  Stopped: 1
> Images: 14
> Server Version: 17.06.1-ce
> Storage Driver: overlay2
>  Backing Filesystem: extfs
>  Supports d_type: true
>  Native Overlay Diff: true
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins:
>  Volume: local
>  Network: bridge host macvlan null overlay
>  Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
> Swarm: inactive
> Runtimes: runc
> Default Runtime: runc
> Init Binary: docker-init
> containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
> runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
> init version: 949e6fa
> Kernel Version: 4.9.33-mod-std-ipv6-64
> Operating System: Debian GNU/Linux 8 (jessie)
> OSType: linux
> Architecture: x86_64
> CPUs: 4
> Total Memory: 1.927GiB
> Name: ks
> ID: WIZQ:GITW:P4J3:2XHN:Y2JL:VBWO:J4FF:54AL:Y27J:VRMO:UVNW:MEP5
> Docker Root Dir: /var/lib/docker
> Debug Mode (client): false
> Debug Mode (server): false
> Registry: https://index.docker.io/v1/
> Experimental: false
> Insecure Registries:
>  127.0.0.0/8
> Live Restore Enabled: false

docker-compose.yml
> version: '2'
> services:
>   mailserver:

## your full stack mailserver by default ##

>   nginx:
>     image: wonderfall/boring-nginx
>     container_name: nginx
>     # restart: always
>     ports:
>       - "80:8000"
>       - "443:4430"
>     volumes:
>       - /mnt/docker/nginx/sites-enabled:/sites-enabled
>       - /mnt/docker/nginx/conf:/conf.d
>       - /mnt/docker/nginx/log:/var/log/nginx
>       - /mnt/docker/nginx/certs:/certs
>     depends_on:
>       - postfixadmin
>       - rainloop
>       - selfoss


>   selfoss:
>     image: hardware/selfoss
>     container_name: selfoss
>     volumes:
>       - /mnt/docker/selfoss:/selfoss/data


Je pense que si je change le UID/GID en 0000 ça pourrait passer, je t'avoue que je ne comprends pas trop d'où viens mon erreur...

Au fait, merci encore pour ton partage et tes containers

**Comment by hardware** [comment]
https://github.com/hardware/rainloop/issues/10 Quelqu'un a une erreur similaire avec Rainloop pile au même moment... c'est bizarre, je sens que c'est un problème avec le système de fichier et les layers.

**Comment by hardware** [comment]
Ok, that's what I thought, i will try wonderfall/nginx-php:7.1 to solve this problem.

**Comment by hardware** [comment]
Ouais bon c'est bien ça, c'est un problème au niveau du système de fichier et c'est vraiment galère à résoudre, surtout que je peux pas reproduire ton erreur. C'est ce que je te conseille de faire c'est de build l'image en mettant le chmod du run.sh dans le Dockerfile pour voir si ça change quelque chose.

**Comment by Antexa** [comment]
Je ne suis pas sur de comprendre le problème, tu réalises deja un chmod dans ton dockerfile.

```
COPY nginx.conf /etc/nginx/nginx.conf
COPY php-fpm.conf /etc/php7/php-fpm.conf
COPY s6.d /etc/s6.d
COPY run.sh /usr/local/bin/run.sh

RUN chmod +x /usr/local/bin/run.sh /etc/s6.d/*/* /etc/s6.d/.s6-svscan/*

VOLUME /selfoss/data

EXPOSE 8888

CMD ["run.sh"]
```

**Comment by hardware** [comment]
Cette ligne la : 
https://github.com/hardware/selfoss/blob/master/run.sh#L4

Ici :
https://github.com/hardware/selfoss/blob/master/Dockerfile#L48

```
&& apk del build-dependencies \
&& rm -rf /var/cache/apk/* /tmp/* \
&& chown -R $UID:$GID /selfoss /etc/nginx /etc/php7 /var/log /var/lib/nginx /tmp /etc/s6.d
```

**Comment by Antexa** [comment]
J'ai fait un fork pour intégrer ta modification et que être sur que je ne sois pas à coté, je t'avoue que je ne comprends ps l'issue...

https://github.com/Antexa/selfoss/commit/bb1f7bf567aea6aa49b6958e667e378f4f3b0da6

Voila ce que j'ai fait : 
```
git clone https://github.com/Antexa/selfoss && cd selfoss/
sudo docker build -t hardware/selfoss .
```

J'ai une erreur sur s6.d 
> chown: /etc/s6.d: No such file or directory

```
sudo docker-compose stop selfoss
sudo docker-compose rm selfoss
sudo docker-compose up -d
```

Les logs (sudo docker logs -f selfoss ) ne disent plus rien, et quand j'essaie d'atteindre mon URI j'ai une erreur est survenue (avec un 502)

Une idée ?

**Comment by hardware** [comment]
Normalement le dernier commit devrait résoudre ton soucis, peux-tu faire le test ? Merci.

**Comment by Antexa** [comment]
Parfait, tout fonctionne j'arrive a atteindre selfoss sans problème.
