### ISSUE TITLE
ERR_INVALID_REDIRECT after login

### ISSUE THREAD

**Issue by aruhier** [hardware/selfoss#4]
Hi,
When login is enabled in the selfoss configuration, I get an `ERR_INVALID_REDIRECT` error after login. Refreshing the page works, and I am correctly authenticated, so it is not very problematic but I think there is an issue in the nginx configuration.

`baseurl` is set to `/`
I will try to tweak the nginx configuration to see if I can fix the error, if it can help.

Thanks

**Comment by hardware** [comment]
Can you send me your config.ini file please ?

**Comment by aruhier** [comment]
Sure, thanks: https://gist.github.com/Anthony25/63d233d482133cd68403194a3579f7cc

**Comment by Hydrog3n** [comment]
Hello, i update this issue because i have the same issue. 

https://gist.github.com/Hydrog3n/fb40aa9ea3cae789d9133b393fd4ae2f

**Comment by aruhier** [comment]
Fixed since selfoss 2.18
