### ISSUE TITLE
Logging?

### ISSUE THREAD

**Issue by jantman** [hardware/selfoss#6]
I've got selfoss running in this image and it's working via HTTP, but there don't appear to be any logs available, either for nginx or the app. Is there some configuration option I'm missing to enable logging?

**Comment by hardware** [comment]
https://github.com/Wonderfall/dockerfiles/blob/master/nginx-php/7.1/rootfs/nginx/conf/nginx.conf#L14

```
/nginx/logs/access.log
/nginx/logs/error.log
```

**Comment by jantman** [comment]
Oh ok, thanks. I'd expected logs to be coming to STDOUT or STDERR for Docker. This can probably be closed, but I might cut a fork to try and get it to play well with Docker log management.

**Comment by hardware** [comment]
App logs : `/selfoss/data/logs`

In my case, it's not very useful to have the http server logs in docker log management system.
