### ISSUE TITLE
"/var/lib/nginx/logs/error.log" failed (13: Permission denied)

### ISSUE THREAD

**Issue by ahhdem** [hardware/selfoss#9]
from the logs on start.  seems like the nginx uid (100) is unable to write to any of the folders (owned by 991)

I tried the following Dockerfile with no luck as well:
```
FROM hardware/selfoss
ENV CRON_PERIOD 5
RUN /bin/chown -R nginx /var/lib/nginx
RUN /bin/chown -R nginx /var/log/nginx
```

**Comment by hardware** [comment]
Solution :

```yml
environment:
  - UID=nginx
  - GID=nginx
```

https://github.com/mondediefr/docker-flarum/issues/17

**Comment by ahhdem** [comment]
what sorcery is this
```
c571de150aab:/var/lib$ ls -alhrt
total 28
drwxr-xr-x    2 root     root        4.0K Jan  9 19:37 udhcpd
drwxr-xr-x    2 root     root        4.0K Jan  9 19:37 misc
drwxr-xr-x    2 root     root        4.0K Jan  9 19:37 apk
drwxr-xr-x    3 root     root        4.0K Apr  8 06:06 php7
drwxrwxrwx    5 selfoss  991         4.0K Apr 10 19:41 nginx
drwxr-xr-x    9 root     root        4.0K Apr 10 19:41 .
drwxr-xr-x   22 root     root        4.0K Apr 10 19:53 ..
c571de150aab:/var/lib$ id
uid=991(selfoss) gid=991 groups=991
c571de150aab:/var/lib$ cd nginx
-sh: cd: can't cd to nginx
c571de150aab:/var/lib$```

**Comment by hardware** [comment]
> what sorcery is this

Yeah this is a long-time issue, and I have never been able to reproduce this problem on my end, sadly. I think this is related to a docker filesystem issue.

https://github.com/hardware/rainloop/issues/10
https://github.com/mondediefr/docker-flarum/issues/17

If you find another solution, I'd be happy if you share it :)

**Comment by ahhdem** [comment]
ah-hah.. Since it said 'optional' on the readme, I figured those wouldn't be required.  Would it make sense to set the default value from 991 to nginx?  

As it stands, the default configuration does not seem to work for me.  Perhaps it would be worth simply adding the note to the README to try this :) 

Will definitely share if I come across anything better.  Cheers for the quick response! :)
